import Signup from "./application/useCase/Signup";
import GetAccount from "./application/useCase/GetAccount";
import AccountRepository from "./infrastructure/repository/AccountRepository";
import RideRepository from "./infrastructure/repository/RideRepository";
import SolicitateRide from "./application/useCase/SolicitateRide";
import GetRide from "./application/useCase/GetRide";
import PgPromiseAdapter from "./infrastructure/database/DatabaseConnection";
import ExpressAdapter from "./infrastructure/http/HttpServer";
import MainController from "./infrastructure/http/MainController";
import Registry from "./infrastructure/di/Registry";

const httpServer = new ExpressAdapter();
const connection = new PgPromiseAdapter();
const accountRepository = new AccountRepository(connection);
const rideRepository = new RideRepository(connection);
const signup = new Signup(accountRepository);
const getAccount = new GetAccount(accountRepository);
const solicitateRide = new SolicitateRide(accountRepository, rideRepository);
const getRide = new GetRide(rideRepository, accountRepository);
const registry = Registry.getInstance();
registry.register("signup", signup);
registry.register("getAccount", getAccount);
registry.register("solicitateRide", solicitateRide);
registry.register("getRide", getRide);
new MainController(httpServer);
httpServer.listen(3000);
